name: ml-ci-cd
on: [push]
jobs:
  test-and-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - run: pip install -r requirements.txt
      - run: python validate_data.py
      - run: python train.py 200 8
      - name: Cek model gate
        run: python check_model_gate.py 0.70